# Generated by Django 3.2.8 on 2022-09-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_addproduct_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct_tb',
            old_name='categotyid',
            new_name='categoryid',
        ),
    ]
